config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :products
  resources :signup do
    collection do
      get 'step1'
      get 'step2' 
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cards,    dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
    # @users = Users.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:number)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def step1
    @user = User.new
  end
  
  def step2
    @card = Card.new
    session[:user_params_after_step1] = user_params
  end

  def create
    @user = User.new(session[:user_params_after_step1])
    if @user.save
      card_info = card_params.merge({user_id: @user.id})
      @card = Card.new(card_info)
      if @card.save
        redirect_to cards_path
      else
        render '/signup/step1'
      end
    else
      render '/signup/step1'
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name
    )
  end

  def card_params
    params.require(:card).permit(
      :user_id,
      :number
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/cards/_form.html.haml
= form_with(model: card, local: true) do |form|
  - if card.errors.any?
    #error_explanation
      %h2
        = pluralize(card.errors.count, "error")
        prohibited this card from being saved:
      %ul
        - card.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :number
    = form.number_field :number
  .actions
    = form.submit

app/views/cards/edit.html.haml
%h1 Editing Card
= render 'form', card: @card
= link_to 'Show', @card
|
= link_to 'Back', cards_path

app/views/cards/index.html.haml
%p#notice= notice
%h1 Cards
%table
  %thead
    %tr
      %th Number
      %th{:colspan => "3"}
  %tbody
    - @cards.each do |card|
      %tr
        %td= card.number
        %td= link_to 'Show', card
        %td= link_to 'Edit', edit_card_path(card)
        %td= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Card', new_card_path
= link_to 'ログイン' , step1_signup_index_path

app/views/cards/new.html.haml
%h1 New Card
= render "form", card: @card
= link_to 'Back', cards_path

app/views/cards/show.html.haml
%p#notice= notice
%p
  %strong Number:
  = @card.number
= link_to 'Edit', edit_card_path(@card)
|
= link_to 'Back', cards_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ComplexForm
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/signup/step1.html.haml
.single-container
  会員情報入力
  = form_for @user, url: step2_signup_index_path, method: :get do |f|
    nickname
    = f.text_field :name
    = f.submit 'Continue'

app/views/signup/step2.html.haml
.single-container
  カード情報入力
  = form_for @card, url: "/signup", method: :post do |f|
    カード番号
    = f.text_field :number
    = f.submit '送信'